import type { Vm } from 'arm64js';
import {
  EXAMPLES, WELCOME, hephconfig, readme,
} from './examples';
import { fetchAsset, type Release } from './releases';

export type Stage = 'download' | 'boot' | 'packages' | 'install' | 'ready';

export interface Progress {
  stage: Stage;
  /** 0..1 within the stage, when measurable. */
  fraction?: number;
  detail?: string;
}

export interface Booted {
  vm: Vm;
  vcpus: number;
  /** Whether the base setup came from a snapshot rather than being run. */
  restored: boolean;
}

const IMAGE = 'alpine';
// Ask for two vCPUs. An image boots only with a vCPU count it was published
// for, and `alpine` currently ships a single-vCPU build — fall back to that.
const VCPUS = 2;
const PLUGIN_DIR = '/opt/heph/plugins';

// heph and its plugins are glibc builds; Alpine is musl. gcompat bridges the
// two, libgcc carries the unwinder, bash backs the `bash` driver. tcc builds
// COMPAT_SHIM and the C examples, with musl-dev for the libc headers.
const PACKAGES = 'gcompat libgcc libstdc++ bash coreutils tcc tcc-libs tcc-libs-static musl-dev';

// The two glibc symbols gcompat lacks, forwarded to their musl equivalents.
// Preloaded into heph, so the plugins it opens resolve them too. (On arm64 a
// variadic argument travels like a fixed one, so fcntl64 needs no stdarg.)
const COMPAT_SHIM = `int res_init(void);
int fcntl(int, int, ...);
int __res_init(void) { return res_init(); }
int fcntl64(int fd, int cmd, long arg) { return fcntl(fd, cmd, arg); }
`;
const HEPH_BIN = '/opt/heph/bin/heph';
const COMPAT_LIB = '/opt/heph/lib/libhephcompat.so';
// heph's bash completion, generated by the installed release.
const COMPLETION = '/etc/heph-completion.bash';

type SetupStep =
  | { run: string }
  | { write: string; content: string; mode?: number };

/**
 * Everything the VM needs that doesn't depend on the heph release. It runs
 * once, and the VM is then snapshotted; later starts boot that snapshot. The
 * snapshot is keyed on a hash of these steps (see snapshotKey), so editing
 * any of them — a package, the shim, the wrapper — builds a fresh one.
 */
const BASE_SETUP: SetupStep[] = [
  { run: `apk add --no-cache ${PACKAGES}` },
  { write: '/opt/heph/lib/compat.c', content: COMPAT_SHIM },
  { run: `tcc -shared -nostdlib -o ${COMPAT_LIB} /opt/heph/lib/compat.c` },
  {
    write: '/usr/local/bin/heph',
    mode: 0o755,
    content: [
      '#!/bin/sh',
      // The VM is offline: skip the self-update check and telemetry.
      'export HEPH_NO_SELF_UPDATE=1 HEPH_DISABLE_TELEMETRY=1',
      `LD_PRELOAD=${COMPAT_LIB} exec ${HEPH_BIN} "$@"`,
      '',
    ].join('\n'),
  },
  {
    write: '/etc/profile.d/heph.sh',
    content: [
      'export PS1="\\w \\$ "',
      `[ -n "$BASH_VERSION" ] && [ -r ${COMPLETION} ] && . ${COMPLETION}`,
      'cat /etc/heph-welcome',
      '',
    ].join('\n'),
  },
];

// Marks this page's snapshots among any others the origin keeps.
const SNAPSHOT_APP = 'heph-playground';

// Options a plugin refuses to load without. The go plugin needs a toolchain;
// `host` uses the one `apk add go` installs.
const PLUGIN_OPTIONS: Record<string, string> = {
  'heph-go-plugin': '    options:\n      gotool: host\n',
};

/** Run `commands` in one exec, stopping at the first that fails. */
async function run(vm: Vm, commands: string | string[], timeoutMs = 300_000): Promise<string> {
  const command = [commands].flat().join(' && ');
  const { output, exitCode } = await vm.exec(command, { timeoutMs });
  if (exitCode !== 0) {
    throw new Error(`\`${command}\` exited ${exitCode}:\n${output.slice(-2000)}`);
  }
  return output;
}

/** Run `steps` one after another. */
function sequence(steps: (() => Promise<unknown>)[]): Promise<void> {
  return steps.reduce<Promise<void>>(
    (prev, step) => prev.then(async () => { await step(); }),
    Promise.resolve(),
  );
}

async function snapshotKey(): Promise<string> {
  const recipe = JSON.stringify({ image: IMAGE, vcpus: VCPUS, steps: BASE_SETUP });
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(recipe));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function isOurs(meta: unknown, key?: string): boolean {
  const m = meta as { app?: string; key?: string } | null;
  return m?.app === SNAPSHOT_APP && (key === undefined || m.key === key);
}

async function bootFresh(): Promise<{ vm: Vm; vcpus: number }> {
  const { Arm64JS } = await import('arm64js');
  try {
    return { vm: await Arm64JS.boot(IMAGE, { vcpus: VCPUS }), vcpus: VCPUS };
  } catch (e) {
    if (!/vcpu/i.test(String((e as Error)?.message))) throw e;
    return { vm: await Arm64JS.boot(IMAGE, { vcpus: 1 }), vcpus: 1 };
  }
}

/**
 * A VM with BASE_SETUP applied: resumed from this browser's snapshot for the
 * current key when there is one, otherwise booted, set up and snapshotted.
 * Snapshots are an optimisation only — no storage (private window, blocked
 * third-party storage) or a snapshot that won't boot just means a full setup.
 */
async function bootBase(onProgress: (p: Progress) => void): Promise<Booted> {
  const { Arm64JS } = await import('arm64js');
  const key = await snapshotKey();
  const snapshots = await Arm64JS.snapshots.list().catch(() => []);

  const hit = snapshots.find((s) => isOurs(s.meta, key));
  if (hit) {
    onProgress({ stage: 'boot', detail: 'from snapshot' });
    try {
      return { vm: await Arm64JS.boot(hit.id), vcpus: hit.vcpus, restored: true };
    } catch {
      await Arm64JS.snapshots.remove(hit.id, { force: true }).catch(() => {});
    }
  }

  onProgress({ stage: 'boot' });
  const { vm, vcpus } = await bootFresh();
  try {
    onProgress({ stage: 'packages', detail: PACKAGES });
    await sequence(BASE_SETUP.map((step) => () => ('run' in step
      ? run(vm, step.run)
      : vm.writeFile(step.write, step.content, { mode: step.mode }))));

    onProgress({ stage: 'packages', detail: 'saving snapshot', fraction: 0 });
    try {
      await vm.snapshot({
        name: 'heph playground base',
        meta: { app: SNAPSHOT_APP, key },
        onProgress: (done, total) => onProgress({
          stage: 'packages', detail: 'saving snapshot', fraction: total ? done / total : undefined,
        }),
      });
      // Drop the snapshots of earlier setups.
      await Promise.all(snapshots
        .filter((s) => isOurs(s.meta) && !isOurs(s.meta, key))
        .map((s) => Arm64JS.snapshots.remove(s.id, { force: true }).catch(() => {})));
    } catch {
      // No storage here: the next start sets up from scratch again.
    }
  } catch (e) {
    vm.dispose();
    throw e;
  }
  return { vm, vcpus, restored: false };
}

/**
 * Download heph + every plugin of `release`, get a set-up VM, and install
 * them. Plugins are mounted read-only (no VM memory); the binary is written
 * into the VM because it has to be executable. None of it is in the
 * snapshot, so one snapshot serves every release.
 */
export async function bootPlayground(
  release: Release,
  onProgress: (p: Progress) => void,
  signal: AbortSignal,
): Promise<Booted> {
  // --- download, one asset at a time ---------------------------------------
  const names = [release.binary, ...release.plugins.flatMap((p) => [p.manifest, p.lib])];
  const total = names.reduce((n, name) => n + (release.sizes[name] ?? 0), 0);
  let finished = 0;
  const report = (current: number) => {
    const d = finished + current;
    onProgress({
      stage: 'download',
      fraction: total ? Math.min(d / total, 1) : undefined,
      detail: `${(d / 2 ** 20).toFixed(0)} / ${(total / 2 ** 20).toFixed(0)} MiB`,
    });
  };
  report(0);

  // The VM boots and sets up meanwhile; its progress shows once the downloads
  // are done, so the two don't fight over the progress display.
  let downloading = true;
  let baseProgress: Progress = { stage: 'boot' };
  const basing = bootBase((p) => {
    baseProgress = p;
    if (!downloading) onProgress(p);
  });
  // Surfaced below, after the downloads; don't let it go unhandled meanwhile.
  basing.catch(() => {});

  const assets = new Map<string, Blob>();
  try {
    // Sequential: the proxy drops concurrent streams.
    await sequence(names.map((name) => async () => {
      const blob = await fetchAsset(release, name, report, signal);
      assets.set(name, blob);
      finished += blob.size;
    }));
  } catch (e) {
    basing.then(({ vm }) => vm.dispose(), () => {});
    throw e;
  }
  downloading = false;
  onProgress(baseProgress);

  const booted = await basing;
  const { vm } = booted;
  if (signal.aborted) {
    vm.dispose();
    throw new DOMException('aborted', 'AbortError');
  }

  try {
    onProgress({ stage: 'install', detail: 'heph binary' });
    await vm.writeFile(HEPH_BIN, assets.get(release.binary)!, { mode: 0o755 });

    // Rewrite each manifest to point at the mounted library instead of its
    // download URL, so heph loads plugins without network access.
    const manifests = await Promise.all(release.plugins.map(async (p) => {
      const text = await assets.get(p.manifest)!.text();
      const m = JSON.parse(text) as { name: string; version?: string };
      return [p.manifest, new Blob([JSON.stringify({
        name: m.name,
        version: m.version,
        artifacts: [{ os: 'linux', arch: 'arm64', path: `./${p.lib}` }],
      }, null, 2)])] as const;
    }));
    const mounted: Record<string, Blob> = Object.fromEntries([
      ...manifests,
      ...release.plugins.map((p) => [p.lib, assets.get(p.lib)!] as const),
    ]);
    const entries = release.plugins
      .map((p) => `  - path: ${PLUGIN_DIR}/${p.manifest}\n${PLUGIN_OPTIONS[p.stem] ?? ''}`)
      .join('');
    if (release.plugins.length) {
      onProgress({ stage: 'install', detail: `${release.plugins.length} plugins` });
      await vm.mount(mounted, PLUGIN_DIR);
    }

    onProgress({ stage: 'install', detail: 'examples' });
    const config = hephconfig(entries);
    const files = EXAMPLES.flatMap((ex): [string, string][] => {
      const root = `/root/examples/${ex.dir}`;
      return [
        [`${root}/.hephconfig`, config],
        [`${root}/README`, readme(ex)],
        ...Object.entries(ex.files).map(([path, content]): [string, string] => [`${root}/${path}`, content]),
      ];
    });
    const pluginNames = release.plugins.map((p) => p.stem.replace(/^heph-|-plugin$/g, ''));
    files.push(['/etc/heph-welcome', WELCOME(release.tag, EXAMPLES, pluginNames)]);
    // One script of heredocs instead of a round-trip per file: much faster.
    const script = files.map(([path, content]) => (
      `mkdir -p '${path.replace(/\/[^/]+$/, '')}'\ncat > '${path}' <<'HEPH_PLAYGROUND_EOF'\n${content}${content.endsWith('\n') ? '' : '\n'}HEPH_PLAYGROUND_EOF\n`
    )).join('');
    await vm.writeFile('/tmp/heph-install.sh', script);
    await run(vm, [
      // Mounts the image lacks: pseudo-terminals for `heph run --shell`, and,
      // for the examples, a filesystem with extended attributes, which
      // `codegen = "copy"` needs (the root filesystem has none).
      'mountpoint -q /dev/pts || { mkdir -p /dev/pts && mount -t devpts devpts /dev/pts; }',
      'mkdir -p /root/examples && { mountpoint -q /root/examples || mount -t tmpfs tmpfs /root/examples; }',
      'sh /tmp/heph-install.sh',
      'rm /tmp/heph-install.sh',
      // Releases without `heph tool completions` just go without completion.
      `{ heph tool completions bash > ${COMPLETION} 2>/dev/null || rm -f ${COMPLETION}; }`,
      'heph version',
    ]);
  } catch (e) {
    vm.dispose();
    throw e;
  }

  onProgress({ stage: 'ready' });
  return booted;
}

/** Hand the console to the visitor: a login bash in the examples directory. */
export function enterShell(vm: Vm): Promise<void> {
  return vm.write('clear; cd /root/examples && exec bash -l\r');
}
