import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Documentation sidebar. Kept explicit (rather than autogenerated) so the
 * placeholder structure reads as an intentional information architecture:
 * a getting-started track, core concepts, and reference.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      collapsible: false,
      items: ['intro', 'getting-started'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsible: false,
      items: [
        'concepts/targets',
        'concepts/dependencies',
        'concepts/reproducibility',
        'concepts/caching',
        'concepts/sandbox',
        'concepts/codegen',
        'concepts/approval',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      items: ['guides/first-build', 'guides/consuming-outputs', 'guides/ci', 'guides/validate', 'guides/formatting-build-files', 'guides/remote-cache', 'guides/inspecting-builds', 'guides/editor-setup', 'guides/claude-code-plugin'],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsible: false,
      items: [
        'plugins/index',
        'plugins/buildfile',
        'plugins/exec',
        'plugins/fs',
        'plugins/go',
        'plugins/group',
        'plugins/hostbin',
        'plugins/http-fetch',
        'plugins/nix',
        'plugins/query',
        'plugins/textfile',
        'plugins/gha',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      items: ['reference/configuration', 'reference/addresses', 'reference/cli'],
    },
  ],
};

export default sidebars;
