import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Documentation sidebar. Kept explicit (rather than autogenerated) so the
 * placeholder structure reads as an intentional information architecture:
 * a getting-started track, core concepts, and reference.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/targets', 'concepts/reproducibility'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/cli'],
    },
  ],
};

export default sidebars;
